Object.assign(window.I18N.bn, {
  'ab.title': 'আমাদের কথা | হিসাব', 'ab.desc': 'হিসাব বাংলাদেশের মানুষের জন্য বানানো ফ্রি বাংলা ও ইংরেজি ক্যালকুলেটর সাইট। জানুন আমরা কারা ও কেন বানিয়েছি।', 'ab.h1': 'আমাদের কথা',
  'ab.body': '<h2>হিসাব কী</h2><p>হিসাব বাংলাদেশের মানুষের জন্য বানানো একটি ফ্রি ক্যালকুলেটর সাইট। টাকা কথায়, জমির হিসাব, লোন EMI, DPS ও FDR, যাকাত এবং আয়কর, সব এক জায়গায়, বাংলা ও ইংরেজিতে।</p><h2>কেন বানানো হয়েছে</h2><p>চেক লেখা, জমি কেনা, লোন নেওয়া বা যাকাত হিসাব করা, এসব কাজে ছোট ভুলও বড় ক্ষতি করতে পারে। অথচ বাংলায় সহজ ও নির্ভরযোগ্য টুল কম। হিসাব সেই ফাঁক ভরতে চায়।</p><h2>নির্ভুলতা নিয়ে আমাদের নীতি</h2><p>প্রতিটি টুলের গাণিতিক সূত্র আমরা পরীক্ষা করে নিই, আর পেজে সূত্র ও হালনাগাদের তারিখ দেওয়া থাকে। ব্যাংকের সুদের হার, জমির মাপ ও কর নিয়ম বদলায়, তাই বড় সিদ্ধান্তের আগে সংশ্লিষ্ট প্রতিষ্ঠানে যাচাই করুন।</p><h2>খরচ কীভাবে চলে</h2><p>সব টুল ফ্রি। ভবিষ্যতে সাইটে বিজ্ঞাপন থাকতে পারে, তা থেকেই সাইট চালানোর খরচ আসবে।</p><h2>আপনার মতামত</h2><p>ভুল পেলে বা নতুন টুল চাইলে আমাদের জানান। ঠিকানা <a data-int="contact.html" href="contact.html">যোগাযোগ</a> পাতায় আছে।</p>',
  'ct.title': 'যোগাযোগ | হিসাব', 'ct.desc': 'হিসাবে ভুল পেলে বা নতুন ক্যালকুলেটরের পরামর্শ থাকলে ইমেইলে যোগাযোগ করুন।', 'ct.h1': 'যোগাযোগ',
  'ct.body': '<p>প্রশ্ন, ভুলের খবর বা নতুন টুলের পরামর্শ থাকলে ইমেইল করুন:</p><p><a href="mailto:{{email}}"><b>{{email}}</b></a></p><p>আমরা সাধারণত কয়েক দিনের মধ্যে উত্তর দেওয়ার চেষ্টা করি।</p><h2>ভুল জানাতে চাইলে</h2><p>কোন টুলে, কী সংখ্যা দিয়েছিলেন এবং কী ফলাফল পেয়েছেন, তা লিখে পাঠান। তাহলে আমরা সহজে ভুল খুঁজে বের করতে পারব।</p><h2>নতুন টুলের অনুরোধ</h2><p>কোন ক্যালকুলেটর আপনার কাজে লাগবে, তা ইমেইলে জানান। বেশি অনুরোধ পাওয়া টুল আগে বানানো হবে।</p>',
  'pv.title': 'গোপনীয়তা নীতি | হিসাব', 'pv.desc': 'হিসাব আপনার কোন তথ্য নেয় বা রাখে, কুকি ও বিজ্ঞাপন নিয়ে আমাদের গোপনীয়তা নীতি।', 'pv.h1': 'গোপনীয়তা নীতি',
  'pv.body': '<p>এই পাতায় বলা আছে হিসাব (Hishab) আপনার কোন তথ্য নেয় বা রাখে।</p><h2>আমরা ব্যক্তিগত তথ্য সংগ্রহ করি না</h2><p>হিসাবে সাইন-আপ বা লগইন নেই। ক্যালকুলেটরে আপনি যে সংখ্যা লেখেন, তা আপনার ফোন বা কম্পিউটারের ব্রাউজারেই হিসাব হয়। সেই সংখ্যা আমাদের কাছে পাঠানো বা জমা করা হয় না।</p><h2>আপনার ডিভাইসে যা সংরক্ষিত হয়</h2><p>আপনার বেছে নেওয়া ভাষা (বাংলা বা ইংরেজি) ব্রাউজারে সংরক্ষিত থাকে, যাতে পরের বার একই ভাষায় সাইট খোলে। এটি শুধু আপনার ডিভাইসে থাকে।</p><h2>কুকি ও আপনার পছন্দ</h2><p>প্রথমবার সাইটে এলে আমরা কুকি নিয়ে আপনার পছন্দ জানতে চাই। বিজ্ঞাপন সাইটটি ফ্রি রাখতে সাহায্য করে। "গ্রহণ করুন" বাছলে বিজ্ঞাপন আপনার আগ্রহ অনুযায়ী ব্যক্তিগতকৃত হতে পারে, এজন্য কুকি ব্যবহার হয়। "প্রত্যাখ্যান" বাছলেও বিজ্ঞাপন দেখবেন, তবে তা ব্যক্তিগতকৃত হবে না। বিজ্ঞাপন সরবরাহকারী বিজ্ঞাপন দেখানো ও জালিয়াতি ঠেকানোর মতো প্রয়োজনীয় কাজে কিছু কুকি ব্যবহার করতে পারে। আপনার পছন্দ ব্রাউজারে ১২ মাস সংরক্ষিত থাকে এবং পাতার নিচের "কুকি সেটিংস" থেকে যেকোনো সময় বদলানো যায়।</p><h2>হোস্টিং ও লগ</h2><p>সাইটটি যে হোস্টিং সেবায় চলে (যেমন Cloudflare), সেই সেবা নিরাপত্তা ও কার্যকারিতার জন্য সাধারণ প্রযুক্তিগত লগ রাখতে পারে, যেমন আইপি অ্যাড্রেস ও ব্রাউজারের ধরন। হিসাব এসব তথ্য দিয়ে কাউকে শনাক্ত করার চেষ্টা করে না।</p><h2>বিজ্ঞাপন</h2><p>ভবিষ্যতে সাইটে Google AdSense-এর মতো তৃতীয় পক্ষের বিজ্ঞাপন দেখানো হতে পারে। এসব সরবরাহকারী আপনার আগের ভিজিটের ভিত্তিতে বিজ্ঞাপন দেখাতে কুকি ব্যবহার করতে পারে। Google-এর বিজ্ঞাপন সেটিংস (adssettings.google.com) থেকে আপনি ব্যক্তিগতকৃত বিজ্ঞাপন বন্ধ করতে পারেন।</p><h2>তৃতীয় পক্ষের সেবা</h2><p>পেজ দেখাতে আমরা Google Fonts ও আইকন সরবরাহকারীর মতো সেবা ব্যবহার করি। আপনার ব্রাউজার সরাসরি এসব সেবার সঙ্গে যোগাযোগ করে।</p><h2>যোগাযোগ</h2><p>গোপনীয়তা নিয়ে প্রশ্ন থাকলে ইমেইল করুন: <a href="mailto:{{email}}">{{email}}</a></p><p>নীতি বদলালে এই পাতা হালনাগাদ করা হবে।</p>',
  'tm.title': 'শর্তাবলি | হিসাব', 'tm.desc': 'হিসাব সাইট ব্যবহারের শর্ত: ফলাফল শুধু ধারণার জন্য, দায় সীমা ও অন্যান্য নিয়ম।', 'tm.h1': 'শর্তাবলি',
  'tm.body': '<p>হিসাব সাইট ব্যবহার করলে আপনি নিচের শর্তগুলো মেনে নিচ্ছেন বলে ধরা হবে।</p><h2>শুধু ধারণার জন্য</h2><p>এই সাইটের সব ফলাফল আনুমানিক এবং শুধু ধারণার জন্য। এগুলো আর্থিক, আইনি, কর বা ধর্মীয় পরামর্শ নয়। বড় সিদ্ধান্তের আগে ব্যাংক, ভূমি অফিস, NBR বা সংশ্লিষ্ট বিশেষজ্ঞের সঙ্গে যাচাই করুন।</p><h2>নির্ভুলতা</h2><p>আমরা হিসাব যতটা সম্ভব নির্ভুল রাখার চেষ্টা করি। তবে সুদের হার, জমির মাপ, কর নিয়ম ও অন্যান্য তথ্য সময় ও এলাকাভেদে বদলায়। কোনো তথ্য পুরোনো বা ভুল হতে পারে।</p><h2>দায় সীমা</h2><p>এই সাইটের ফলাফলের ওপর ভিত্তি করে নেওয়া কোনো সিদ্ধান্তের ফলে হওয়া ক্ষতির দায় আমরা নিই না। সাইটটি যেমন আছে তেমনভাবে দেওয়া হয়।</p><h2>বিজ্ঞাপন ও বাইরের লিংক</h2><p>সাইটে বিজ্ঞাপন বা বাইরের সাইটের লিংক থাকতে পারে। সেসব সাইটের বিষয়বস্তুর দায় আমাদের নয়।</p><h2>মেধাস্বত্ব</h2><p>সাইটের ডিজাইন, লেখা ও কোড আমাদের। অনুমতি ছাড়া বাণিজ্যিকভাবে কপি করা যাবে না। ব্যক্তিগত ব্যবহারের জন্য ফলাফল কপি ও শেয়ার করতে পারেন।</p><h2>পরিবর্তন</h2><p>আমরা যেকোনো সময় টুল, তথ্য বা এই শর্তাবলি বদলাতে পারি।</p><h2>যোগাযোগ</h2><p>প্রশ্ন থাকলে ইমেইল করুন: <a href="mailto:{{email}}">{{email}}</a></p>'
});
Object.assign(window.I18N.en, {
  'ab.title': 'About | Hishab', 'ab.desc': 'Hishab is a free Bangla and English calculator site built for the people of Bangladesh. Learn who we are and why we built it.', 'ab.h1': 'About us',
  'ab.body': '<h2>What is Hishab</h2><p>Hishab is a free calculator site built for the people of Bangladesh. Taka in words, land converter, loan EMI, DPS and FDR, zakat and income tax, all in one place, in Bangla and English.</p><h2>Why we built it</h2><p>When you write a cheque, buy land, take a loan or work out zakat, even a small mistake can be costly. Yet simple, reliable tools in Bangla are rare. Hishab wants to fill that gap.</p><h2>Our approach to accuracy</h2><p>We test the formulas behind every tool, and each page shows its sources and the date it was last updated. Bank rates, land measures and tax rules change, so please check with the relevant institution before big decisions.</p><h2>How we cover costs</h2><p>Every tool is free. The site may show ads in the future, and that is what will cover the running costs.</p><h2>Your feedback</h2><p>If you find a mistake or want a new tool, tell us. The address is on the <a data-int="contact.html" href="contact.html">Contact</a> page.</p>',
  'ct.title': 'Contact | Hishab', 'ct.desc': 'Found a mistake in Hishab or want a new calculator? Get in touch by email.', 'ct.h1': 'Contact',
  'ct.body': '<p>For questions, mistakes you found or tool suggestions, email us:</p><p><a href="mailto:{{email}}"><b>{{email}}</b></a></p><p>We usually try to reply within a few days.</p><h2>Reporting a mistake</h2><p>Tell us which tool you used, what numbers you entered and what result you got. That helps us find the problem quickly.</p><h2>Requesting a new tool</h2><p>Email us which calculator would help you. The most requested tools get built first.</p>',
  'pv.title': 'Privacy policy | Hishab', 'pv.desc': 'What information Hishab collects or keeps, and our policy on cookies and ads.', 'pv.h1': 'Privacy policy',
  'pv.body': '<p>This page explains what information Hishab collects or keeps about you.</p><h2>We do not collect personal information</h2><p>Hishab has no signup or login. The numbers you type into a calculator are worked out in your own browser, on your phone or computer. They are not sent to us or stored by us.</p><h2>What is saved on your device</h2><p>Your chosen language (Bangla or English) is saved in your browser so the site opens in the same language next time. It stays on your device only.</p><h2>Cookies and your choice</h2><p>On your first visit we ask for your choice about cookies. Ads help keep Hishab free. If you choose "Accept", ads may be personalised to your interests, which uses cookies. If you choose "Reject", you will still see ads, but they will not be personalised. Ad providers may still use some cookies needed to deliver ads and prevent fraud. Your choice is saved in your browser for 12 months and you can change it any time from "Cookie settings" at the bottom of the page.</p><h2>Hosting and logs</h2><p>The hosting service the site runs on (such as Cloudflare) may keep standard technical logs for security and performance, such as IP address and browser type. Hishab does not use this information to identify anyone.</p><h2>Advertising</h2><p>In the future the site may show third-party ads such as Google AdSense. These providers may use cookies to show ads based on your earlier visits. You can turn off personalised ads in Google\'s ad settings (adssettings.google.com).</p><h2>Third-party services</h2><p>To display pages we use services such as Google Fonts and an icon provider. Your browser contacts these services directly.</p><h2>Contact</h2><p>For privacy questions, email: <a href="mailto:{{email}}">{{email}}</a></p><p>If this policy changes, this page will be updated.</p>',
  'tm.title': 'Terms | Hishab', 'tm.desc': 'Terms for using Hishab: results are for guidance only, limits of liability and other rules.', 'tm.h1': 'Terms of use',
  'tm.body': '<p>By using Hishab you agree to the terms below.</p><h2>For guidance only</h2><p>All results on this site are estimates and for guidance only. They are not financial, legal, tax or religious advice. Before big decisions, check with your bank, land office, NBR or the relevant expert.</p><h2>Accuracy</h2><p>We try to keep the calculations as accurate as we can. But interest rates, land measures, tax rules and other facts change over time and by area. Some information may be out of date or wrong.</p><h2>Limit of liability</h2><p>We are not responsible for any loss from decisions made using the results on this site. The site is provided as it is.</p><h2>Ads and external links</h2><p>The site may contain ads or links to other sites. We are not responsible for the content of those sites.</p><h2>Intellectual property</h2><p>The design, text and code of the site are ours. They may not be copied commercially without permission. You can copy and share results for your own use.</p><h2>Changes</h2><p>We may change the tools, the information or these terms at any time.</p><h2>Contact</h2><p>For questions, email: <a href="mailto:{{email}}">{{email}}</a></p>'
});
